config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :games
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Defines the root path route ("/")
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/sign_in', to: 'sessions#new', as: :new_session
  get '/logout', to: 'sessions#destroy'

  resources :cats do
    resources :moves, only: [:create]
  end

  resources :four_lines do
    resources :moves, only: [:create]
  end

  resources :hangmen do
    resources :moves, only: [:create]
  end
end

app/models/four_line.rb
class FourLine < ApplicationRecord
  belongs_to :user
  broadcasts

  before_validation on: :create do
    self.state = {
      current_symbol: ['x', 'o'].sample,
      winner_state: false,
      board: {
        0 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil },
        1 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil },
        2 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil },
        3 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil },
        4 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil },
        5 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil },
        6 => { 0 => nil, 1 => nil, 2 => nil, 3 => nil, 4 => nil, 5 => nil, 6 => nil }
      }
    }
  end

  def move row, col
    self.state['board'][row.to_s][col.to_s] = self.state['current_symbol']
    self.state['current_symbol'] = self.state['current_symbol'] == 'x' ? 'o' : 'x'
    self.save!
  end
end

app/controllers/four_lines_controller.rb
# frozen_string_literal: true

class FourLinesController < ApplicationController
  def index
    @four_lines = FourLine.all
  end

  def show
    @four_line = FourLine.find params[:id]
  end

  def create
    redirect_to FourLine.create
  end
end

app/helpers/four_lines_helper.rb
# frozen_string_literal: true

module FourLinesHelper
end

app/views/four_lines/_four_line.html.erb
<div id="<%= dom_id(four_line) %>" class="four_in_line_game">
  <% 6.times do |row| %>
    <div class='row  cat_row_<%=row%>'>
      <% 7.times do |col| %>
      <span class='cell cat_col_<%=col%>'>
        <% unless four_line.state['board'][row.to_s][col.to_s].nil? %>
          <span class='cell four_team_<%=four_line.state['board'][row.to_s][col.to_s] %>'>o</span>
        <% else %>
          <% game = Game.last %>
          <%= button_to 'o', four_line_moves_path(four_line), params: { game_id: game.id, col: col, row: row } %>
        <% end %>
      </span>
      <% end %>
    </div>
  <% end %>

  <br><% four_line.state.each do |element| %>
    <%= element %><br>
  <% end %><br>
</div>

app/views/four_lines/create.html.erb
<h1>FourLines#create</h1>
<p>Find me in app/views/four_lines/create.html.erb</p>

app/views/four_lines/index.html.erb
<h1>FourLines#index</h1>
<p>Find me in app/views/four_lines/index.html.erb</p>

app/views/four_lines/show.html.erb
<h1>FourLines#show</h1>
<p>Find me in app/views/four_lines/show.html.erb</p>