config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :games
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Defines the root path route ("/")
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/sign_in', to: 'sessions#new', as: :new_session
  get '/logout', to: 'sessions#destroy'

  resources :cats do
    resources :moves, only: [:create]
  end

  resources :four_lines do
    resources :moves, only: [:create]
  end

  resources :hangmen do
    resources :moves, only: [:create]
  end
end

app/models/game.rb
class Game < ApplicationRecord
  broadcasts

  def register_user user
    @users = self.players.nil? ? Hash.new : self.players
    @users.store(user.id, user.email) unless @users.has_key?(user.id) == true
    self.players = @users
    self.save!
  end

  def set_game name: nil, sort: nil, id: nil
    self.data = { name: name, sort: sort, game_id: id }
    self.save!
  end
end

app/controllers/games_controller.rb
# frozen_string_literal: true

class GamesController < ApplicationController
  before_action :user_is_logged_in?
  before_action :set_game, only: %i[show edit update destroy]

  # GET /games or /games.json
  def index
    @games = Game.all
  end

  # GET /games/1 or /games/1.json
  def show; end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit; end

  # POST /games or /games.json
  def create
    @game = Game.new(game_params)

    respond_to do |format|
      if @game.save
        format.html { redirect_to game_url(@game), notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1 or /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to game_url(@game), notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1 or /games/1.json
  def destroy
    @game.destroy

    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_game
    @game = Game.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def game_params
    params.require(:game).permit(:data, :players, :state, :result, :statistics)
  end
end

app/helpers/games_helper.rb
# frozen_string_literal: true

module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game) do |form| %>
  <% if game.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
        <% game.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.text_field :data %>
  </div>

  <div>
    <%= form.label :players, style: "display: block" %>
    <%= form.text_field :players %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :result, style: "display: block" %>
    <%= form.text_field :result %>
  </div>

  <div>
    <%= form.label :statistics, style: "display: block" %>
    <%= form.text_field :statistics %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_game.html.erb
<div id="<%= dom_id game %>" class="game_board">

  <p>
    <strong>Data:</strong>
    <%= game.data %>
  </p>

  <p>
    <strong>Players:</strong>
    <%= game.players %>
  </p>

  <p>
    <strong>State:</strong>
    <% case game.data['sort'] %>
    <% when 'cat' %>
      <% @cat = Cat.find game.data['game_id'] %>
      <%= turbo_stream_from @cat %>
      <div id="<%= dom_id(@cat) %>">
        <%= render @cat %>
      </div>
    <% when 'four_lines' %>
      <% @four_lines = FourLine.find game.data['game_id'] %>
      <%= turbo_stream_from @four_lines %>
      <div id="<%= dom_id(@four_lines) %>">
        <%= render @four_lines %>
      </div>
    <% when 'hangman' %>
    <% @hangman = Hangman.find game.data['game_id'] %>
    <%= turbo_stream_from @hangman %>
    <div id="<%= dom_id(@hangman) %>">
      <%= render @hangman, game: game %>
    </div>    
    <% end %>
  </p>

  <p>
    <strong>Result:</strong>
    <%#= game.result %>
  </p>

  <p>
    <strong>Statistics:</strong>
    <%#= game.statistics %>
  </p>

</div>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Show this game", @game %> |
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/index.html.erb
<div class="lobby">
  <div> 
    <h1><%= params[:name].upcase.gsub("_", " ") %></h1>
  </div>
  <div> 
    <%= current_user.email %><br>
  </div>
  <div> 

    <% game = Game.create %>

    <% case params[:name] %>
      <% when 'cat' %>
      <% cat = Cat.create! user_id: current_user.id %>
      <% game.set_game name: params[:name], sort: 'cat', id: cat.id %>
      <% when 'four_lines' %>
      <% four_lines = FourLine.create! user_id: current_user.id %>
      <% game.set_game name: params[:name], sort: 'four_lines', id: four_lines.id %>
      <% when 'hangman' %>
      <% hangman = Hangman.create! user_id: current_user.id %>
      <% game.set_game name: params[:name], sort: 'hangman', id: hangman.id %>
    <% end %>
    <a href="<%= game_path(game) %>" class="animated-button1">
      <span></span>
      <span></span>
      <span></span>
      <span></span>
      Start Game
    </a>
  </div>
</div>

app/views/games/new.html.erb
<h1>New game</h1>

<%= render "form", game: @game %>

<br>

<div>
  <%= link_to "Back to games", games_path %>
</div>

app/views/games/register_user.turbo_stream.erb
<%= turbo_stream.update dom_id(@game) do %>
  <%= render @game %>
<% end %>

app/views/games/show.html.erb
<%= turbo_stream_from @game %>
<% @game.register_user current_user %>

<%= tag.div id: dom_id(@game) do %>
  <%= render @game %>
<% end %>