config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'home#index'

  resources :games
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  # Defines the root path route ("/")
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/sign_in', to: 'sessions#new', as: :new_session
  get '/logout', to: 'sessions#destroy'

  resources :cats do
    resources :moves, only: [:create]
  end

  resources :four_lines do
    resources :moves, only: [:create]
  end

  resources :hangmen do
    resources :moves, only: [:create]
  end
end

app/models/cat.rb
class Cat < ApplicationRecord
  belongs_to :user
  broadcasts

  before_validation on: :create do
    self.state = {
      current_symbol: ['x', 'o'].sample,
      winner_state: false,
      board: {
        0 => { 0 => nil, 1 => nil, 2 => nil },
        1 => { 0 => nil, 1 => nil, 2 => nil },
        2 => { 0 => nil, 1 => nil, 2 => nil }
      }
    }
  end

  def move row, col
    self.state['board'][row.to_s][col.to_s] = self.state['current_symbol']
    self.state['current_symbol'] = self.state['current_symbol'] == 'x' ? 'o' : 'x'
    self.save!
  end
end

app/controllers/cats_controller.rb
# frozen_string_literal: true

class CatsController < ApplicationController
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find params[:id]
  end

  def create
    redirect_to Cat.create
  end
end

app/helpers/cats_helper.rb
# frozen_string_literal: true

module CatsHelper
end

app/views/cats/_cat.html.erb
<div id="<%= dom_id(cat) %>" class="cat_game">
  <% 3.times do |row| %>
    <div class='row cat_row_<%=row%>'>
      <% 3.times do |col| %>
      <span class='cell cat_col_<%=col%>'>
        <% unless cat.state['board'][row.to_s][col.to_s].nil? %>
          <%= cat.state['board'][row.to_s][col.to_s] %>
        <% else %>
          <% game = Game.last %>
          <%= button_to cat.state['current_symbol'], cat_moves_path(cat), params: { game_id: game.id, col: col, row: row } %>
        <% end %>
      </span>
      <% end %>
    </div>
  <% end %>

  <br>
  <% cat.state.each do |element| %>
    <%= element %><br>
  <% end %><br>
</div>

app/views/cats/create.html.erb
<h1>Cats#create</h1>
<p>Find me in app/views/cats/create.html.erb</p>

app/views/cats/index.html.erb
<h1>Cats#index</h1>
<p>Find me in app/views/cats/index.html.erb</p>

app/views/cats/show.html.erb
<h1>Cats#show</h1>
<p>Find me in app/views/cats/show.html.erb</p>